[package]
name = "frontier-template-node"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate Node template"
edition = "2018"
license = "Apache-2.0"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.3.4"
log = "0.4.8"
structopt = "0.3.8"
jsonrpc-core = "14.2.0"
jsonrpc-pubsub = "14.2.0"

sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-cli = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-executor = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-service = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-network = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-consensus = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-consensus = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
pallet-evm = { git = "https://github.com/labsofficial/substrate.git", branch = "v0.3-hotfixes-fee=0-test" }
pallet-ethereum = { path = "../../frame/ethereum" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }

frontier-consensus = { path = "../../consensus" }
frontier-template-runtime = { path = "../runtime" }
frontier-rpc = { path = "../../rpc" }
frontier-rpc-primitives = { path = "../../rpc/primitives" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate.git", branch = "rococo-branch" }
